#
# ╔═══════════════════════════════════════════════════╗
# ║                  ┌──╮                             ║
# ║            ╲ ╱   ├──╯┌─╮ ╭──╮ ╲ ╱  ╲ ╱            ║
# ║            ╱ ╲   │   │   ╰──╯ ╱ ╲   │             ║
# ╚═══════════════════════════════════════════════════╝
# ɪɴɴᴏᴠᴀᴛɪᴠᴇ ᴄᴏᴍᴍᴜɴɪᴄᴀᴛɪᴏɴ ʙʀɪᴅɢᴇ ꜰᴏʀ ᴘʀᴏxɪᴇꜱ ᴀɴᴅ ꜱᴇʀᴠᴇʀꜱ
#

# do not forward this port unless you know what you are doing
port: 25599

# clients without this code will be unable to connect
auth-code: P@ssword

# display all packets to console
show-packets: true


# Minecraft Settings

# You must have xProxy ranks selected in your ProxyChat plugin for the ranks to sync properly
enable-xProxy-ranks: true






# enables verbose output
debug: false
