#
# ╔═══════════════════════════════════════════════════╗
# ║                  ┌──╮                             ║
# ║            ╲ ╱   ├──╯┌─╮ ╭──╮ ╲ ╱  ╲ ╱            ║
# ║            ╱ ╲   │   │   ╰──╯ ╱ ╲   │             ║
# ╚═══════════════════════════════════════════════════╝
# ɪɴɴᴏᴠᴀᴛɪᴠᴇ ᴄᴏᴍᴍᴜɴɪᴄᴀᴛɪᴏɴ ʙʀɪᴅɢᴇ ꜰᴏʀ ᴘʀᴏxɪᴇꜱ ᴀɴᴅ ꜱᴇʀᴠᴇʀꜱ
#

# do not forward this port
port: 25599

# clients without this code will be unable to connect
auth-code: 'connectPassword'